import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import fp from "fastify-plugin";

const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Request ID middleware.
 *
 * - Accepts an incoming `x-request-id` header and uses it as the request ID
 *   when it is a valid UUID v4 string.
 * - Generates a new UUID when the header is absent or invalid.
 * - Always echoes the final request ID back in the `x-request-id` response header.
 *
 * Register this plugin BEFORE the request logger so that `request.id` is
 * already set to the correct value when the first log entry is emitted.
 */
async function requestIdPlugin(fastify: FastifyInstance) {
  fastify.addHook(
    "onRequest",
    async (request: FastifyRequest, reply: FastifyReply) => {
      const incoming = request.headers["x-request-id"];

      if (typeof incoming === "string" && UUID_REGEX.test(incoming)) {
        // Reuse the caller-supplied ID — cast needed because Fastify types
        // expose `id` as readonly after construction.
        (request as unknown as { id: string }).id = incoming;
      }
      // If absent or invalid, request.id already holds the UUID generated by
      // Fastify's genReqId (configured in src/index.ts).

      reply.header("x-request-id", request.id);
    }
  );
}

export const requestIdMiddleware = fp(requestIdPlugin);
